添加 直接使用微信小程序的自定义组件weui 组件 的演示代码
remaxjs/remax pull request #1453
Opened 2020-12-22 03:43 UTC by anuxs

分享直接使用微信小程序的自定义组件weui 组件的演示代码，避免其他人再去摸索

2020-12-22 04:03 UTC, Darmody commented
![LGTM](http://www.reactiongifs.com/r/spa.gif)

2020-12-26 06:18 UTC, hehex9 requested changes
please check the preview url (https://remax-git-fork-anuxs-patch-1.remaxjs.vercel.app/guide/basic/custom-component) first

2020-12-26 06:18 UTC, hehex9 commented on docs/guide/basic/custom-component.md
> +### 然后直接使用微信小程序的自定义组件weui 组件
rm

2020-12-26 06:18 UTC, hehex9 commented on docs/guide/basic/custom-component.md
> +```
\```js

2020-12-26 06:18 UTC, hehex9 commented on docs/guide/basic/custom-component.md
> +import { View} from 'remax/wechat';
import { View } from 'remax/wechat';

2020-12-26 06:18 UTC, hehex9 commented on docs/guide/basic/custom-component.md
> +// 引入 Cells、Cell 组件 （React要求组件名首字母大写）
rm

2020-12-26 06:18 UTC, hehex9 commented on docs/guide/basic/custom-component.md
> +            <view>标题文字（使用slot）</view>
`<View>` ?

2020-12-26 06:18 UTC, hehex9 commented on docs/guide/basic/custom-component.md
> +export default () => (
add an empty line before `export`

2020-12-28 04:03 UTC, anuxs reviewed
对修改建议做了更改。

2020-12-28 04:45 UTC, hehex9 commented on docs/guide/basic/custom-component.md
> +          <Cell>
mind the indent

```js
<Cell value="标题文字" footer="说明文字"></Cell>
<Cell>
  ...
</Cell>
```

2020-12-28 06:32 UTC, anuxs reviewed
再次修改了代码缩进。非常抱歉。

2020-12-28 06:35 UTC, hehex9 approved these changes

2020-12-29 02:25 UTC, merged